SKID: bookmarks, simply kept in directories

* Motivation

Great post by GradHacker: [[http://www.gradhacker.org/2012/08/13/towards-better-pdf-management-with-the-filesystem/][Towards Better PDF Management with the Filesystem]].

Tools for organizing your PDFs are restrictive and proprietary (in the sense
that information is kept hostage inside the software).

Article advocates
 1. use file system: helps avoid the "proprietary data problem"
 2. flat structure: keeping a single (flat) directory of all your papers
 3. tags over folders: well-known problem we all faced before gmail.
 4. conventions: naming conventions, tagging conventions
 5. simple scripts: they don't say it directly (author is a mac user, not a
    linux geek), but they talk about using simple programs rather large
    monolithic programs.

=skid= stores all documents in a single directory called "the cache". Each file
in the cache has a directory associated with it where metadata will live
(e.g. user notes, bibliographic information, text extraction). These directories
are named after the cached document with a simple '.d' suffix (for example,
cached document =Cookbook.pdf= has a directory =Cookbook.pdf.d/=). The most
important file living in this directory is =notes.org=. This file is where the
user annotates documents with bibliographic metadata (e.g. title, author, year),
and personal notes.

With the basic setup we can quick write tools for maintaining, accessing, and
analyzing the repository of documents.


* FAQ

 - What if I don't want to write notes about a specific single paper, but rather
   on a topic or something?

   Create an empty document and write your notes it's notes.org file.


* Org-mode configuration

Support for 'skid:' direction in org-mode links

: ;;------------------------------------------------------------------------------
: ;; Support for skid links
: ;;
: ;; USAGE:
: ;;
: ;; The link directive 'skid'
: ;;
: ;;  [[skid:author:"Jason Eisner"][Jason Eisner]]
: ;;
: ;; Programmatic
: ;;
: ;;  (skid-search "tags:related:discrete-backprop")
: ;;  (skid-search "machine learning")
: ;;
: ;; org-mode reference http://orgmode.org/org.html#Adding-hyperlink-types
:
: (require 'org)
:
: (org-add-link-type "skid" 'skid-search)
:
: (defun skid-search (query)
:   "skid tag search."
:   (interactive)
:   (switch-to-buffer (make-temp-name "Skid"))
:   (insert (shell-command-to-string (concat "python -m skid search --format org --limit 0 " query)))
:   (beginning-of-buffer)
:   (org-mode))
: ;;------------------------------------------------------------------------------
